### ISSUE TITLE
Передавать сразу готовую сущьность из PL

### ISSUE THREAD

**Issue by isaikin** [epanteleeva/EPAM_summer_practice#1]
https://github.com/epanteleeva/EPAM_summer_practice/blob/9438e50b49e6084d1ff0d56a4f513a042b142db1/Epam.UsersAndAwards/Epam.UsersAndAwards.Logic/AwardLogic.cs#L20

Нужно предавать готовую сущность

**Comment by epanteleeva** [comment]
Исправила
