### ISSUE TITLE
Это не нужно, просто скорее всего никогда не зайдет

### ISSUE THREAD

**Issue by isaikin** [epanteleeva/EPAM_summer_practice#2]
https://github.com/epanteleeva/EPAM_summer_practice/blob/9438e50b49e6084d1ff0d56a4f513a042b142db1/Epam.UsersAndAwards/Epam.UsersAndAwards.Logic/AwardLogic.cs#L34

**Comment by epanteleeva** [comment]
Удалила такого рода строки
